# Generated by Django 5.0.7 on 2025-11-24 07:15

import diagnostic.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('legal_structure', models.CharField(blank=True, max_length=100)),
                ('owner_background', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('key_partners', models.TextField(blank=True)),
                ('full_time_employees_total', models.IntegerField(default=0)),
                ('full_time_employees_female', models.IntegerField(default=0)),
                ('part_time_employees_total', models.IntegerField(default=0)),
                ('part_time_employees_female', models.IntegerField(default=0)),
                ('revenue_this_year', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('revenue_last_year', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('units_sold_this_year', models.CharField(blank=True, max_length=100)),
                ('units_sold_last_year', models.CharField(blank=True, max_length=100)),
                ('num_suppliers', models.IntegerField(blank=True, null=True)),
                ('num_customers', models.IntegerField(blank=True, null=True)),
                ('total_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('short_term_plans', models.TextField(blank=True)),
                ('medium_term_plans', models.TextField(blank=True)),
                ('long_term_plans', models.TextField(blank=True)),
                ('market_linkage_needs', models.TextField(blank=True)),
                ('finance_needs_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('key_assistance_areas', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('section_scores', models.JSONField(default=dict)),
                ('priorities', models.JSONField(default=dict)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='diagnostic.enterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=6)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, help_text='Assignee initials or identifier', max_length=128)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('inprogress', 'In Progress'), ('completed', 'Completed')], default='todo', max_length=16)),
                ('order', models.IntegerField(default=0, help_text='Position within the status column')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='diagnostic.enterprise')),
            ],
            options={
                'ordering': ['status', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_notifications', models.BooleanField(default=True, help_text='Enable email notifications for important updates')),
                ('push_notifications', models.BooleanField(default=False, help_text='Enable push notifications on your device')),
                ('weekly_reports', models.BooleanField(default=True, help_text='Receive weekly summary reports')),
                ('marketing_communications', models.BooleanField(default=False, help_text='Receive marketing and promotional emails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=10)),
                ('priority', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('descriptors', models.JSONField(help_text='Rubric for scores 0..4')),
                ('evidence_prompt', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diagnostic.category')),
            ],
            options={
                'unique_together': {('category', 'number')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(help_text='0..4, or -1 for NA')),
                ('evidence', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='diagnostic.enterprise')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='diagnostic.question')),
            ],
            options={
                'unique_together': {('enterprise', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=diagnostic.models.evidence_attachment_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='diagnostic.questionresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('section_scores', models.JSONField(default=dict)),
                ('priorities', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_summary', to='diagnostic.enterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('MEMBER', 'Member')], default='MEMBER', max_length=16)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('REMOVED', 'Removed')], default='INVITED', max_length=16)),
                ('invitation_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('invitation_expires_at', models.DateTimeField(blank=True, help_text='When this invitation expires', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='diagnostic.enterprise')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_team_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_members',
                'unique_together': {('enterprise', 'email')},
            },
        ),
    ]
