# Generated by Django 5.0.7 on 2025-11-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_alter_teammember_invitation_expires_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'number'], name='diagnostic__categor_110f76_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category'], name='diagnostic__categor_0a170e_idx'),
        ),
    ]
