# Generated by Django 5.0.7 on 2025-11-24 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='invitation_expires_at',
            field=models.DateTimeField(blank=True, help_text='When this invitation expires', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
