# Generated by Django 5.0.7 on 2025-11-27 15:34

import diagnostic.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_question_diagnostic__categor_110f76_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, help_text='Team member assigned to this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_action_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the action was marked complete', null=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who marked this action as complete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_action_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the action item'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Percentage of completion (0-100)'),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Assignee initials or identifier (legacy)', max_length=128),
        ),
        migrations.CreateModel(
            name='ActionItemDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=diagnostic.models.action_document_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('description', models.TextField(blank=True)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='diagnostic.actionitem')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_action_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('progress_update', models.IntegerField(blank=True, help_text='Progress percentage at time of note', null=True)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='diagnostic.actionitem')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
