# Generated by Django 5.2.6 on 2025-10-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0010_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitem',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Assignee initials or identifier', max_length=128),
        ),
    ]
