# Generated by Django 5.2.6

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0011_alter_actionitem_assigned_to'),
    ]

    operations = [
        # Fields already exist in model - placeholder migration
    ]
