# Generated by Django 5.0.7 on 2025-10-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0012_teammember_invitation_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='emailotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
