# Generated by Django 5.0.7 on 2025-11-07 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0013_alter_emailotp_options_emailotp_is_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'verbose_name': 'Notification Preference', 'verbose_name_plural': 'Notification Preferences'},
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Enable email notifications for important updates'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='marketing_communications',
            field=models.BooleanField(default=False, help_text='Receive marketing and promotional emails'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_notifications',
            field=models.BooleanField(default=False, help_text='Enable push notifications on your device'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='weekly_reports',
            field=models.BooleanField(default=True, help_text='Receive weekly summary reports'),
        ),
        migrations.AlterModelTable(
            name='teammember',
            table='team_members',
        ),
    ]
