# Generated by Django 5.2.6 on 2025-09-16 15:56

import diagnostic.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('legal_structure', models.CharField(blank=True, max_length=100)),
                ('owner_background', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('key_partners', models.TextField(blank=True)),
                ('full_time_employees_total', models.IntegerField(default=0)),
                ('full_time_employees_female', models.IntegerField(default=0)),
                ('part_time_employees_total', models.IntegerField(default=0)),
                ('part_time_employees_female', models.IntegerField(default=0)),
                ('revenue_this_year', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('revenue_last_year', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('units_sold_this_year', models.CharField(blank=True, max_length=100)),
                ('units_sold_last_year', models.CharField(blank=True, max_length=100)),
                ('num_suppliers', models.IntegerField(blank=True, null=True)),
                ('num_customers', models.IntegerField(blank=True, null=True)),
                ('total_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('short_term_plans', models.TextField(blank=True)),
                ('medium_term_plans', models.TextField(blank=True)),
                ('long_term_plans', models.TextField(blank=True)),
                ('market_linkage_needs', models.TextField(blank=True)),
                ('finance_needs_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('key_assistance_areas', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=10)),
                ('priority', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('descriptors', models.JSONField(help_text='Rubric for scores 0..4')),
                ('evidence_prompt', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=4)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diagnostic.category')),
            ],
            options={
                'unique_together': {('category', 'number')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(help_text='0..4, or -1 for NA')),
                ('evidence', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='diagnostic.enterprise')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='diagnostic.question')),
            ],
            options={
                'unique_together': {('enterprise', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=diagnostic.models.evidence_attachment_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='diagnostic.questionresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('section_scores', models.JSONField(default=dict)),
                ('priorities', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_summary', to='diagnostic.enterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
